#=============================================================================
# Copyright (C) 2013 Daniel Pfeifer <daniel@pfeifer-mail.de>
#
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#=============================================================================

language: cpp

compiler: gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libarchive-dev libboost-filesystem-dev re2c valac-0.16

script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DKARROT_USE_ARCHIVE=ON  -DKARROT_USE_PACKAGEKIT=ON ..
  - cmake --build .
  - ctest -V

branches:
  only:
    - develop
    - master
