#=============================================================================
# Copyright (C) 2013 Daniel Pfeifer <daniel@pfeifer-mail.de>
#
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#=============================================================================

language: cpp

compiler:
  - clang
  - gcc

env:
  global:
    - OPTIONS="-DKARROT_USE_ARCHIVE=ON -DKARROT_USE_PACKAGEKIT=ON -DKARROT_USE_SUBVERSION=ON"
    - DEPENDS="libarchive-dev valac-0.16 libsvn-dev"
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

matrix:
  include:
    - compiler: i686-w64-mingw32-gcc
      env:
        - BUILD_TYPE=Release
        - OPTIONS="-DCMAKE_TOOLCHAIN_FILE=../CMake/i686-w64-mingw32.cmake"
        - DEPENDS="g++-mingw-w64-i686"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends $DEPENDS docbook-xml docbook-xsl doxygen libboost-filesystem-dev libboost-program-options-dev re2c xsltproc

script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE $OPTIONS ..
  - cmake --build .
  - ctest -V
  - cmake --build . --target documentation

branches:
  only:
    - develop
    - master
