#=============================================================================
# Copyright (C) 2013 Daniel Pfeifer <daniel@pfeifer-mail.de>
#
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#=============================================================================

language: cpp

compiler:
  - clang
  - gcc

env:
  global:
    - OPTIONS="-DKARROT_USE_ARCHIVE=ON -DKARROT_USE_PACKAGEKIT=ON -DKARROT_USE_SUBVERSION=ON"
    - DEPENDS="libarchive-dev valac-0.16 libsvn-dev"
    - TARGETS="all test"
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

matrix:
  allow_failures:
    - compiler: clang
  include:
    - compiler: gcc
      env:
        - BUILD_TYPE=Release
        - OPTIONS="-DCMAKE_TOOLCHAIN_FILE=../CMake/i686-w64-mingw32.cmake -DKARROT_BUILD_TOOL=OFF"
        - DEPENDS="binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686"
        - TARGETS="all test VERBOSE=1"
    - compiler: gcc
      env:
        - BUILD_TYPE=Release
        - OPTIONS="-DKARROT_BUILD_DOCS=ON"
        - DEPENDS="docbook-xml docbook-xsl doxygen xsltproc"
        - TARGETS="documentation"

before_install:
  - sudo apt-get install -qq --no-install-recommends $DEPENDS libboost-filesystem-dev libboost-program-options-dev re2c

script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE $OPTIONS .. && make -k $TARGETS

branches:
  only:
    - develop
    - master
