#=============================================================================
# Copyright (C) 2013 Daniel Pfeifer <daniel@pfeifer-mail.de>
#
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#   http://www.boost.org/LICENSE_1_0.txt
#=============================================================================

language: cpp

compiler:
  - clang
  - gcc

env:
  - OPTIONS="-DCMAKE_BUILD_TYPE=Debug"
  - OPTIONS="-DCMAKE_BUILD_TYPE=Release"

script:
  - mkdir _build
  - cd _build
  - cmake $OPTIONS ..
  - cmake --build .
  - ctest -V

branches:
  only:
    - develop
    - master
