/*
 * Copyright (C) 2013 Daniel Pfeifer <daniel@pfeifer-mail.de>
 *
 * Distributed under the Boost Software License, Version 1.0.
 * See accompanying file LICENSE_1_0.txt or copy at
 *   http://www.boost.org/LICENSE_1_0.txt
 */

#ifndef KARROT_CMAKE_HPP
#define KARROT_CMAKE_HPP

#include <karrot.hpp>

#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include <boost/algorithm/string/case_conv.hpp>

namespace CMake
{

class Listsfile
  {
  public:
    void add_prefix(const std::string& prefix)
      {
      prefixes.push_back(prefix);
      }
    void add_subdir(const std::string& name, const Karrot::Dictionary& variant)
      {
      subdirs << '\n';
      variant.foreach([&](const char *key, const char *val)
        {
        subdirs
          << "set("
          << boost::to_upper_copy(name + '_' + key)
          << " \""
          << val
          << "\")\n"
          ;
        });
      subdirs << "add_subdirectory(" << name << ")\n";
      }
    void write() const
      {
      std::ofstream out("CMakeLists.txt");
      out << "# Generated by Karrot 0.1\n\n";
      out << "cmake_minimum_required(VERSION 2.8 FATAL_ERROR)\n";
      out << "project(Workspace NONE)\n\n";
      if (!prefixes.empty())
        {
        out << "list(APPEND CMAKE_PREFIX_PATH\n";
        for (const std::string& prefix : prefixes)
          {
          out << "  \"${Workspace_SOURCE_DIR}/" << prefix << "\"\n";
          }
        out << "  )\n";
        }
      out << subdirs.rdbuf();
      }
  private:
    std::vector<std::string> prefixes;
    std::stringstream subdirs;
  };

class Injector: public Karrot::DriverDecorator
  {
  public:
    Injector(Listsfile& listsfile, std::unique_ptr<Driver>&& component)
        : listsfile(listsfile), Karrot::DriverDecorator(std::move(component))
      {
      }
  private:
    void download(const Karrot::Implementation& impl, bool requested) //override
      {
      DriverDecorator::download(impl, requested);
      if(impl.component() == std::string("SOURCE"))
        {
        listsfile.add_subdir(impl.name(), impl.variant());
        }
      else
        {
        listsfile.add_prefix(impl.name());
        }
      }
  private:
    Listsfile& listsfile;
  };

} // namespace CMake

#endif /* KARROT_CMAKE_HPP */
